### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### Send POST request with json body
POST localhost:8080/v1/taborets
Content-Type: application/json

{
  "name": "my taboret",
  "description": "super taboret"
}

### GET exist taboret
GET http://localhost:8080/v1/taborets/1


### GET not exist taboret
GET http://localhost:8080/v1/taborets/12

###
GET https://v3.football.api-sports.io/status
x-rapidapi-host:v3.football.api-sports.io
x-rapidapi-key:3a263e195713aaef25d730cc3cbca2f9



###
GET https://apiv3.apifootball.com/api/?action=get_countries&APIkey=eee5028bd4f1a9645f0de3b18aa4c17c11a0eedd815aeaacf2cae4d5801e8969